# Generated by Django 5.1 on 2024-08-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0002_contacts_e_mail_contacts_phone_no_contacts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
